from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QMainWindow

class Ui_MainWindow(QMainWindow):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 800)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.mdiArea = QtWidgets.QMdiArea(self.centralwidget)
        self.mdiArea.setGeometry(QtCore.QRect(259, 0, 940, 751))
        self.mdiArea.setObjectName("mdiArea")
        self.trvDocFiles = QtWidgets.QTreeView(self.centralwidget)
        self.trvDocFiles.setGeometry(QtCore.QRect(0, 454, 256, 297))
        self.trvDocFiles.setObjectName("trvDocFiles")
        self.trvOSDirs = QtWidgets.QTreeView(self.centralwidget)
        self.trvOSDirs.setGeometry(QtCore.QRect(0, 0, 256, 451))
        self.trvOSDirs.setObjectName("trvOSDirs")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1200, 22))
        self.menubar.setObjectName("menubar")
        self.menu_F = QtWidgets.QMenu(self.menubar)
        self.menu_F.setObjectName("menu_F")
        self.menu_A = QtWidgets.QMenu(self.menubar)
        self.menu_A.setObjectName("menu_A")
        self.menu_W = QtWidgets.QMenu(self.menubar)
        self.menu_W.setObjectName("menu_W")
        self.menu_H = QtWidgets.QMenu(self.menubar)
        self.menu_H.setObjectName("menu_H")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actClose = QtGui.QAction(MainWindow)
        self.actClose.setObjectName("actClose")
        self.actCloseAll = QtGui.QAction(MainWindow)
        self.actCloseAll.setObjectName("actCloseAll")
        self.actTile = QtGui.QAction(MainWindow)
        self.actTile.setObjectName("actTile")
        self.actCasCade = QtGui.QAction(MainWindow)
        self.actCasCade.setObjectName("actCasCade")
        self.actNext = QtGui.QAction(MainWindow)
        self.actNext.setObjectName("actNext")
        self.actPrev = QtGui.QAction(MainWindow)
        self.actPrev.setObjectName("actPrev")
        self.actSave = QtGui.QAction(MainWindow)
        self.actSave.setObjectName("actSave")
        self.actQuit = QtGui.QAction(MainWindow)
        self.actQuit.setObjectName("actQuit")
        self.actAbout = QtGui.QAction(MainWindow)
        self.actAbout.setObjectName("actAbout")
        self.actSpeak = QtGui.QAction(MainWindow)
        self.actSpeak.setObjectName("actSpeak")
        self.actAboutPyQt = QtGui.QAction(MainWindow)
        self.actAboutPyQt.setObjectName("actAboutPyQt")
        self.actWord = QtGui.QAction(MainWindow)
        self.actWord.setObjectName("actWord")
        self.actCloud = QtGui.QAction(MainWindow)
        self.actCloud.setObjectName("actCloud")
        self.actCrawl = QtGui.QAction(MainWindow)
        self.actCrawl.setObjectName("actCrawl")
        self.actRecog = QtGui.QAction(MainWindow)
        self.actRecog.setObjectName("actRecog")
        self.menu_F.addAction(self.actSave)
        self.menu_F.addSeparator()
        self.menu_F.addAction(self.actQuit)
        self.menu_A.addAction(self.actSpeak)
        self.menu_A.addAction(self.actWord)
        self.menu_A.addAction(self.actCloud)
        self.menu_A.addSeparator()
        self.menu_A.addAction(self.actCrawl)
        self.menu_A.addSeparator()
        self.menu_A.addAction(self.actRecog)
        self.menu_W.addAction(self.actClose)
        self.menu_W.addAction(self.actCloseAll)
        self.menu_W.addSeparator()
        self.menu_W.addAction(self.actTile)
        self.menu_W.addAction(self.actCasCade)
        self.menu_W.addSeparator()
        self.menu_W.addAction(self.actNext)
        self.menu_W.addAction(self.actPrev)
        self.menu_H.addAction(self.actAbout)
        self.menu_H.addSeparator()
        self.menu_H.addAction(self.actAboutPyQt)
        self.menubar.addAction(self.menu_F.menuAction())
        self.menubar.addAction(self.menu_A.menuAction())
        self.menubar.addAction(self.menu_W.menuAction())
        self.menubar.addAction(self.menu_H.menuAction())
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menu_F.setTitle(_translate("MainWindow", "文件(&F)"))
        self.menu_A.setTitle(_translate("MainWindow", "分析(&A)"))
        self.menu_W.setTitle(_translate("MainWindow", "窗口(&W)"))
        self.menu_H.setTitle(_translate("MainWindow", "帮助(&H)"))
        self.actClose.setText(_translate("MainWindow", "关闭"))
        self.actCloseAll.setText(_translate("MainWindow", "关闭所有"))
        self.actTile.setText(_translate("MainWindow", "平铺(&T)"))
        self.actCasCade.setText(_translate("MainWindow", "层叠(&C)"))
        self.actNext.setText(_translate("MainWindow", "下一个(&N)"))
        self.actPrev.setText(_translate("MainWindow", "前一个(&P)"))
        self.actSave.setText(_translate("MainWindow", "保存(&S)"))
        self.actQuit.setText(_translate("MainWindow", "退出(&Q)"))
        self.actAbout.setText(_translate("MainWindow", "关于(&A)"))
        self.actSpeak.setText(_translate("MainWindow", "朗读(&R)"))
        self.actAboutPyQt.setText(_translate("MainWindow", "关于PyQt 6"))
        self.actWord.setText(_translate("MainWindow", "分词(&W)"))
        self.actCloud.setText(_translate("MainWindow", "生成词云"))
        self.actCrawl.setText(_translate("MainWindow", "爬取信息"))
        self.actRecog.setText(_translate("MainWindow", "识别文字"))